

services:

  wordpress:
    build: ./requirements/wordpress/
    restart: always
    container_name: wordpress
    env_file:
      - .env
    networks:
      - Shared
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx/
    restart: always
    container_name: nginx
    env_file:
      - .env
    networks:
      - Shared
    volumes:
      - wordpress:/var/www/html/
    ports:
      - "443:443"
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb/
    restart: always
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - Shared

networks:
  Shared:
    name: Shared

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: local
      o: bind
      device: /home/m-boukel/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      type: local
      o: bind
      device: /home/m-boukel/data/mariadb